### ISSUE TITLE
How to install the child theme?

### ISSUE THREAD

**Issue by grayspace** [deviodigital/cleanblog-child#1]
Hi, great work on porting this theme over to WordPress! I got the main Clean Blog theme installed, but when I tried to install this child theme, it says it is broken. Any ideas? I used the theme uploader feature in the admin. Thanks!

**Comment by robertdevore** [comment]
Can you let me know what the error message says?

I've installed it through the theme uploader feature on two separate installs and it worked both times for me.

**Comment by grayspace** [comment]
After uploading...

> This theme requires a parent theme. Checking if it is installed…
> 
> The parent theme could not be found. You will need to install the parent theme, cleanblog, before you >can use this child theme.
> 
> Theme installed successfully.

And on the installed themes page...

> Broken Themes
> 
> The following themes are installed but incomplete. Themes must have a stylesheet and a template.
> 
> Clean Blog Child - The parent theme is missing. Please install the "cleanblog" parent theme.

But, I already installed the cleanbog theme, and I tried installing the child with the parent active as well as with another theme active. Still no go.

**Comment by robertdevore** [comment]
It may be an issue with the way github has `cleanblog-master` as the folder name, instead of `cleanblog` which is what the child theme checks for.

Are you able to get check the folder name for the `cleanblog-master` folder, and change it to `cleanblog` through your host?

That _should_ fix the issue

**Comment by robertdevore** [comment]
I'm going to go ahead and close this issue for now. If the issue still persists, let me know and I can look into it again.
